POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaW52IiwiaWQiOiI2OTcyODBkODBiNjhjNjllMjIzNzExOGYiLCJpYXQiOjE3NjkxMTI5MDB9.RwIKofs8tyTyydnl7VqPb1sBz1xwVyZiCeC2T9MUKYQ

{
    "title": "To be deleted",
    "author": "Rain Veskus",
    "url": "http://www.myurl.fi/tobedeleted"
}
