name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: osa11
    steps:
      - uses: actions/checkout@v6
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
          INCLUDES: ${{ contains('skipping some stuff', '#skip') }}
        run: echo "$COMMIT_MESSAGES $INCLUDES" 
