name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: osa11
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "New version of `software` is ready!!!"
          description: |
            Version `${{ github.event.release.tag_name }}`
            Click [here](${{ github.event.release.html_url }}) to download!
          color: 0xff91a4
